config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # Sessions routes
  get 'logout', :to => 'sessions#destroy'
  resources :sessions

  # Passwords routes
  get 'passworrds/new'
  get 'passworrds/forgot'
  get 'passworrds/new_reset'
  get 'passworrds/reset'

  # Users routes
  resources :users do

    member do
      get :delete
    end

    member do
      get :show_answers
    end

    collection do
      get :about_developers
    end

    collection do
      get :show_users
    end

    collection do
      get :search
    end

    collection do
      get :search_user
    end

  end

  # Subjects routes
  resources :subjects do

    member do
      get :delete
    end

    member do
      get :subject_questions
    end

    member do
      get :unanswered
    end

    member do
      get :answered
    end

    collection do
      get :search
    end

    collection do
      get :search_subject
    end

    member do
      get :delete_question
    end

  end

  # Questions routes
  resources :questions do

    collection do
      get :unanswered
    end

    collection do
      get :answered
    end

    collection do
      get :search
    end

    member do
      get :delete
    end

    member do
      get :delete_question
    end

    member do
      get :d
    end

  end

  # Answers routes
  resources :answers do

    member do
      get :delete
    end

    member do
      get :rank_answer
    end

    member do
      get :create_comment
    end

    member do
      get :new_comment
    end

  end


end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id            :bigint(8)        not null, primary key
#  title         :text
#  question      :text
#  user_id       :bigint(8)
#  subject_id    :bigint(8)
#  answers_count :integer          default(0)
#  views_count   :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Question < ApplicationRecord

    ##-----------------------------Reqiurments--------------------##
    # Ex:- scope :active, -> {where(:active => true)}
    scope :newest, -> { order( "created_at DESC" ) }
    scope :unanswered, -> { where( answers_count: 0 ) }
    scope :answered, -> { where( "answers_count > 0" ) }
    


    ##--------------------------Assocciations-------------------##
    has_many :answers, dependent: :destroy
    belongs_to :user, counter_cache: true
    belongs_to :subject, counter_cache: true


    ##-----------------------------Callbacks--------------------##

    ##-----------------------------Validations--------------------##
    validates :title, presence: true

    validates :question, presence: true,   
                            uniqueness: true
    
    
    ##-----------------------------Enums-------------------------##
    ##-----------------------------Class methods------------------##

    ##-----------------------------Methods------------------------##
    
    def set_views
        self.views_count += 1
        save!
    end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  layout 'admin'

  def index
    # @questions = Question.ransack( title_cont: "w" ).result
    @questions = Question.newest
    flash[:search] = params[:search]
  end

  def unanswered
    @questions = Question.unanswered
    render('index')
  end

  def answered
    @questions = Question.answered
    render('index')
  end

  def search
    @questions = Question.ransack( title_cont: params[:search] ).result
    render('index')
  end

  def show
    @question = Question.find( params[:id] )
    @question.set_views
    session[:question_id] = @question.id
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    # flash[:subject_id] = params[:question][:subject_id]
    # return render('new')
    @question = Question.new( question_params )

    if @question.save
      flash[:create_question] = nil
      redirect_to(questions_path)
    else
      flash[:create_question] = @question.errors.full_messages
      render('new')
    end
  end

  def d
    @question = Question.new
    flash[:subject_id] = params[:id]
    # if @subject
      # redirect_to(questions_path)
    # else
      render('new')
    # end
  end

  def edit
    @question = Question.find( params[:id] )
  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(question_params)
      redirect_to(question_path(@question))
    else
      render('edit')
    end
  end

  def delete
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to(user_path(@current_user))
  end

  def delete_question
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to(questions_path)
  end

  def destroy
    
  end


  private

  def question_params
    params[:question][:user_id] = @current_user.id
    params.require(:question).permit( :title ,:question, :subject_id, :user_id )
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="ask_main" >
    <div>
    <%= form_for(@question) do |f| %>
        <ul id="ulask">
            <li>
                <label for="">Title</label>   
            </li>
            <li>
                <%= f.text_area(:title, :size => '112x1') %>
            </li>
            <li>
                <label>Quastion</label>
            </li>
            <li>
                <%= f.text_area(:question, :size => '112x20') %>
            </li>
            <li>
                <div class="related_sub">
                    <label for="">Related Subject</label>
                    <%= f.select(:subject_id, Subject.all.map {|s| [ s.name, s.id ] } ) %>
                    <%= f.submit("Update Question") %>
                </div>
            </li>

        </ul>
    <% end %>
    </div>      
</main>

<div class="right_side">
        <div class="right_div">
            <h3 class="right_div_h3">How to Ask?</h3>
            
            <strong class="right_div_strong">Is your question about computer science education?</strong>
            <p class="right_div_p">we prefer question that can be answered;not just discussed <br>
            provide details.<br> share your research </p><br>
        </div>
    </div>

app/views/questions/index.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
        CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="main" class="defult_main">
        <div class="container">

            <div class="mid_ul_1">
                <div class="mid_ul_1_1">
                    <li>
                    <a href="<%= questions_path %>" class="mid_ul_link"> All Quastion </a>
                </li>
                <li>
                    <a href="<%= unanswered_questions_path %>" class="mid_ul_link"> Non Answered  </a>
                </li>
                <li>
                    <a href="<%= answered_questions_path %>" class="mid_ul_link">  Answered  </a>
                </li>
                </div>
                
                <div class="mid_ul_1_2">
                    
                    <li>
                    <a href="" class="mid_ul_link">Last week  </a>
                </li>
                <li>
                    <a href="" class="mid_ul_link"> Last month</a>
                </li>
                </div>

            </div>
            
            <div class="askdiv">
                <a href="<%= new_question_path %>" class="mid_ul_link">Ask Quastion <i class="fas fa-question"></i> </a>
            </div>
        </div>

        <% @questions.each do |question| %>
        <div class="question_container" >
            <div class="quastion_home">
                <div class="quastion_home_1">
                    <h4>Answers</h4>
                    <p> <%= question.answers_count %> </p>
                </div>

                <div class="quastion_home_2">
                    <h4>Views </h4>
                    <p> <%= question.views_count %> </p>
                </div>

                <div class="quastion_home_3">
                    <div class="quastion_home_3_1">
                        <img src="<%= question.user.avatar.url(:thumb)%>" alt="the asker" class="saker">
                        <span> <%= question.user.username %> </span>

                        <p style="display: none"><%= x = false %></p>
                        <% question.answers.each do |answer| %>
                        
                            <% if answer.rank %>
                                <p style="display: none"> <%= x = true %> </p>
                            <% end %>    
                        <% end %>
                        <% if x %>    
                            <i class="fas fa-star" id="star_main"></i>
                        <% else %>
                            <i class="fas fa-star" id="star_main" style="color:white"></i>
                        <% end %>

                        <% if @current_user.admin? %>
                            <a href="<%= delete_question_question_path(question) %>"> Delete</a>
                        <% end %>    
                        <b> <%= question.created_at %> </b>
                    </div>
                <div class="quastion_home_3_2">
                    <div class="quastion_home_3_2_1">
                        <b><a href="<%= question_path(question) %>"> <%= question.title %> </a></b>
                    </div>                    
                </div>
            </div>
        </div>
        <% end %>    
        
        
    </main>



<div class="right_side">
        
    <div class="right_div_table">
        <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>

</div>
<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>



<script>
    function menuToggle(){
        const sidebar = document.getElementById('sidebar')
        
        sidebar.classList.add('active')
        const main = document.getElementById('main')

        const handleClick = function(){
            sidebar.classList.remove('active')
            main.removeEventListener('click', handleClick)
        }

        setTimeout(function(){
            main.addEventListener('click', handleClick)
        }, 100)
        
    }

</script>

app/views/questions/new.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>



<main id="ask_main" >
    <div>
    <%= form_for(@question) do |f| %>
        <ul id="ulask">
            <li>
                <label for="">Title</label>   
            </li>
            <li>
                <%= f.text_area(:title, :size => '112x1') %>
            </li>
            
            <% if flash[:create_question].present? %>
            <li>
                <p style="color:red; margin:2px"> <%= flash[:create_question] %> </p>
            </li> 
            <% end %>
            <li>
                <label>Quastion</label>
            </li>
            <li>
                <%= f.text_area(:question, :size => '112x20') %>
            </li>
            <li>
                <div class="related_sub">
                    <label for="">Related Subject</label>
                    <%= f.select(:subject_id, Subject.all.map {|s| [ s.name, s.id ] } ) %>
                    <%= f.submit("Ask") %>
                </div>
            </li>

        </ul>
    <% end %>
    </div>      
</main>

<div class="right_side">
        <div class="right_div">
            <h3 class="right_div_h3">How to Ask?</h3>
            
            <strong class="right_div_strong">Is your question about computer science education?</strong>
            <p class="right_div_p">we prefer question that can be answered;not just discussed <br>
            provide details.<br> share your research </p><br>
        </div>
        
    </div>
    <script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

    <script>
        function menuToggle(){
            const sidebar = document.getElementById('sidebar')
            
            sidebar.classList.add('active')
            const main = document.getElementById('ask_main')

            const handleClick = function(){
                sidebar.classList.remove('active')
                main.removeEventListener('click', handleClick)
            }

            setTimeout(function(){
                main.addEventListener('click', handleClick)
            }, 100)
            
        }
    
    </script>

app/views/questions/show.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>

<main id="main" class="defult_main">
    <!-- <div class="the_title">
        <strong>the title of quastion </strong>
    </div> -->
    <div class="quastion_home_3_in">
        <div class="quastion_home_3_1 ">
            <img src="<%= @question.user.avatar.url(:thumb)%>" alt="the asker" class="asker">
            <span> <%= @question.user.username %> </span>
            <b> <%= @question.created_at %> </b>
        </div>
        <div class="quastion_home_3_2 quastion_home_3_2_in">
            <div class="title_home3_in">
                <b> <%= @question.title %> </b>
            </div>                    
        </div>
    </div>

    <div class="Qbody" id="scroll" date-simplebar>  
        <pre class="Qbody_sub">
            <%= @question.question %> 
        </pre>
    </div>
    <div class="Q_option">
        <div class="Q_option_1">
            <input value="Answer" type="button" onclick="answer()" class="btn_answer_1">
        </div>
        
        <% if flash[:create_answer].present? %>
            <p style="color:red; margin:2px"> <%= flash[:create_answer] %> </p>
        <% end %>
        
        <div class="Q_option_2" id="answer_body">
            <%= form_tag(answers_path, :method => :post) do %>
                <%= text_area_tag(:answer, params[:answer], size: '105x10') %><br>
                <%= submit_tag("Answer") %>
            <% end %>
        </div>
    </div>

    <% @question.answers.each do |answer| %>  
    <div class="answer">
        <div class="answer_up" >
            <div class="answer_up_left" >
                <% if answer.rank %>
                    <i class="fas fa-star" id="star"></i>
                <% else %>
                    <i class="fas fa-star" id="star" style="color:white"></i>
                <% end %>
                
                <% if @current_user.admin? || @current_user.instructor? %>
                    <a href="<%= rank_answer_answer_path(answer) %>" class="link_rank"> Rank </a> 
                <% end %>
            </div>
            <div class="answer_up_right">
                <div class="quastion_home_3_1 ">
                    <img src="<%= answer.user.avatar.url(:thumb)%>" alt="the asker" class="asker">
                    <span> <%= answer.user.username %> </span>
                    <b> <%= answer.created_at %> </b>
                </div>
                <pre>
                    <%= answer.answer %> 
                </pre>
            </div>
        </div>

        <div class="answer_down" >
                <a href="#"><i class="fas fa-thumbs-up"></i> like</a>
                <a href="#"> <i class="fas fa-thumbs-down"></i> dislike</a>
                <a href="<%= new_comment_answer_path(answer) %>" ><i class="far fa-comment"></i>comment</a>
                <% if @current_user.username == answer.user.username %>
                    <a href="<%= edit_answer_path(answer) %>"><i class="far fa-comment"></i> Update</a>
                    <a href="<%= delete_answer_path(answer) %>"><i class="far fa-comment"></i> Delete</a>
                <% end %>    
        </div>
    </div>
    <% end %>
     
</main>

<div class="right_side" id="right_side">
        
    <div class="right_div_table">
        <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>

</div>   
 
</main>

<script>
    function menuToggle(){
        const sidebar = document.getElementById('sidebar')
        
        sidebar.classList.add('active')
        const main = document.getElementById('main')

        const handleClick = function(){
            sidebar.classList.remove('active')
            main.removeEventListener('click', handleClick)
        }

        setTimeout(function(){
            main.addEventListener('click', handleClick)
        }, 100) 
    }

    function answer(){
    const sidebar = document.getElementById('answer_body')
    
    sidebar.classList.add('active_answer')
    const main = document.getElementById('right_side')

    const handleClick = function(){
        sidebar.classList.remove('active_answer')
        main.removeEventListener('click', handleClick)
    }

    setTimeout(function(){
        main.addEventListener('click', handleClick)
    }, 100)
    
}


</script>