config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # Sessions routes
  get 'logout', :to => 'sessions#destroy'
  resources :sessions

  # Passwords routes
  get 'passworrds/new'
  get 'passworrds/forgot'
  get 'passworrds/new_reset'
  get 'passworrds/reset'

  # Users routes
  resources :users do

    member do
      get :delete
    end

    member do
      get :show_answers
    end

    collection do
      get :about_developers
    end

    collection do
      get :show_users
    end

    collection do
      get :search
    end

    collection do
      get :search_user
    end

  end

  # Subjects routes
  resources :subjects do

    member do
      get :delete
    end

    member do
      get :subject_questions
    end

    member do
      get :unanswered
    end

    member do
      get :answered
    end

    collection do
      get :search
    end

    collection do
      get :search_subject
    end

    member do
      get :delete_question
    end

  end

  # Questions routes
  resources :questions do

    collection do
      get :unanswered
    end

    collection do
      get :answered
    end

    collection do
      get :search
    end

    member do
      get :delete
    end

    member do
      get :delete_question
    end

    member do
      get :d
    end

  end

  # Answers routes
  resources :answers do

    member do
      get :delete
    end

    member do
      get :rank_answer
    end

    member do
      get :create_comment
    end

    member do
      get :new_comment
    end

  end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  username               :string
#  email                  :string
#  password_digest        :string
#  role                   :integer
#  status                 :integer
#  questions_count        :integer          default(0)
#  answers_count          :integer          default(0)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#

class User < ApplicationRecord

    ##-----------------------------Reqiurments--------------------##
    load 'lib/JsonWebToken.rb'
    extend Enumerize
    has_secure_password
    # Ex:- scope :active, -> {where(:active => true)}
    scope :newest, -> { order( "created_at DESC" ) }
    scope :active, -> { where( status: "active" ) }

    ##--------------------------Assocciations-------------------##
    has_many :comments, dependent: :destroy
    has_many :questions, dependent: :destroy
    has_many :answers, dependent: :destroy


    ##-----------------------------Callbacks--------------------##
    before_validation :set_email_dwoncase
   
    
    ##-----------------------------Validations--------------------##
    has_attached_file :avatar , styles: { medium: "300x300>", thumb: "40x40>" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    validates :avatar, presence: true, on: :create

    validates :username, presence: true,   
                            uniqueness: true
                            # length: {minimum:10, maximum:50}

    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
    validates :email, presence: true,
                        uniqueness: true,
                        format: EMAIL_REGEX

    # validates :password, presence: true,   
                            # length: {minimum:9, maximum:20}


    ##-----------------------------Enums------------------------##
    #Enumerize Status
    enumerize :status, in: {
        active: 1,
        unactive: 2
    },default: 1, scope: true, predicates: true

    #Enumerize Role
    enumerize :role, in: {
        admin: 1,
        instructor: 2,
        student: 3
    },default: 3, scope: true, predicates: true


    ##-----------------------------Class methods------------------##

    def self.login login, password 
        user = active.find_by( "username = :login OR email = :login", {login: login} )

        if user && user.authenticate( password )
            user.auth_token
        else
            false
        end
    end

    def generate_password_token!
        self.reset_password_token = generate_token
        self.reset_password_sent_at = Time.now.utc
        self.password = "123456789"
        save!
    end
        
    def password_token_valid?
        (self.reset_password_sent_at + 4.hours) > Time.now.utc
    end
    
    def reset_password!(password)
        self.reset_password_token = nil
        self.password = password
        save!
    end
    

    ##-----------------------------Methods------------------------##

    def login_payload  
        {  
            id:    id,   email: email 
        }
    end


    def auth_token
        JsonWebToken.encode( payload: login_payload )
    end


    private

    def set_email_dwoncase
        self.email = email.downcase if self.email.present?
    end

    def generate_token
        SecureRandom.hex(10)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'admin'

  before_action :set_user, only: [ :show, :show_answers, :edit, :update, :delete ]

  def index
    @users = User.newest
  end

  def show_users
    @users = User.newest
  end

  def show
    @questions = @user.questions
    @show_delete_update = true

  end

  def show_answers
    @answers = @user.answers
    @questions = @answers.map {|a| a.question }.uniq
    @show_delete_update = false
    render('show')
  end

  def search
    @user = User.find( @current_user.id )
    @questions = @user.questions
    @questions = @questions.ransack( title_cont: params[:search] ).result
    @show_delete_update = true
    render('show')
  end

  def search_user
    @users = User.ransack( username_cont: params[:search] ).result
    render('show_users')
  end

  def new
    @user = User.new
  end

  def create
    # Instantiate a new object using form parameters
    @user = User.new( user_params )
    # Save the object
    if @user.save
    # If save succeeds, redirect to the index action
      redirect_to(show_users_users_path)
    else
    # If save fails, redisplay the form so user can fix problems
      flash[:create_user] = @user.errors.full_messages
      render('new')
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to(show_users_users_path)
    else
      render('edit')
    end
  end

  def delete
    @user.destroy
    redirect_to(show_users_users_path)
  end

  def about_developers
  end

  private

  def user_params
    params.require(:user).permit( :username , :password, :email, :role, :status, :avatar )
  end

  def set_user
    @user = User.find( params[:id] )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/#show_answers.html.erb
 <main id="main" class="profile_main defult_main">
        <div class="profile_up2">
            <% if @current_user&.admin? || @current_user&.instructor? %>
                <img class="first" src="/assets/doctors.jpeg" alt="">
            <% else %>
                <img class="first" src="/assets/profile.jpg" alt="">
            <% end %>        
            <div class="profile_up2_1">
                <img src="<%= @user.avatar.url(:medium) %>" alt="pdc" class="profile_img"/>
                <b class="name"> <%= @user.username %> </b>
            </div>
            
        </div>
        <!-- <div class="profile_mid">
            
                <div>
                    <strong>Asks:</strong> 
                    <span> 1</span>
                </div>
                <div>
                    <strong>Answer:</strong>
                    <span> 1 </span>
                </div>
                
        </div> -->
        <div class="container">

                <div class="mid_ul_1">
                    <div class="mid_ul_1_1">
                        <li>
                            <a href="<%= user_path(@current_user) %>" class="mid_ul_link"> All Quastion </a>
                        </li>
                        <li>
                            <a href="<%= show_answers_user_path(@current_user) %>" class="mid_ul_link"> All Answers  </a>
                        </li>
                        
                    </div>
                </div>
        </div>

        <% @answers.each do |answer| %>
        <div class="quastion_home">
            <div class="quastion_home_1">
                <h4>Answers</h4>
                <p> 1 </p>
            </div>

            <div class="quastion_home_3_pro">
                <div class="quastion_home_3_1">
                    <img src="<%= answer.user.avatar.url(:thumb) %>" alt="the asker" class="saker">
                    <span> <%= answer.user.username %> </span>
                        <b> <%= answer.created_at %> </b>
                </div>
                <div class="quastion_home_3_2">
                    <div class="quastion_home_3_2_1">
                        <b><a href="<%= question_path(answer.question) %>"> <%= answer.answer %> </a></b>
                    </div>                    
                </div>
            </div>
            <div class="quastion_home_4">
                <a href="">Update</a>
                <a href="<%= delete_answer_path(answer) %>">Delete</a>
            </div>

        </div>
        <% end %> 

    </main>
    

    <div class="right_side">
        <div class="right_div_table">
                <h3 class="right_div_h3">Personal states</h3>
            <table>
                <!-- <th colspan="2"> states</th> -->
                <tr>
                    <td>Quastions</td>
                    <td> <%= @user.questions.count %> </td>
                </tr>
                <tr>
                    <td>Answers</td>
                    <td> <%= @user.answers.count %> </td>
                </tr>
                <tr>
                    <td>True_answers</td>
                    <td><%= @user.answers.rank_answer.count %></td>
                </tr>
                
            </table>
        </div>
        <% if @current_user&.admin? %>
        <div class="mange_list">
            <h4 class="h4mange">Management</h4>
            <div class="menu">
                <li class="item" id="user">
                    <a href="#user" class="btn"><i class="fas fa-users"> </i> Users</a>
                    <div class="sub_menu">
                        <a href="Add_student.html" class="sub_menu_link " ><i class="fas fa-user-plus" id="mange_icon"></i> Add</a>
                        <a href="" class="sub_menu_link " ><i class="far fa-eye" id="mange_icon"></i></i> Show</a> 
                    </div>
                </li>
                <li class="item" id="subject">
                    <a href="#subject" class="btn"><i class="fas fa-book"> </i> Subject</a>
                    <div class="sub_menu">
                        <a href="" class="sub_menu_link " >Add</a>
                        <a href="" class="sub_menu_link " > <i class="far fa-eye" id="mange_icon"></i></i> Show</a>    
                    </div> 
                </li>
                
            </div>
        </div>
        <% end %>
            <script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

    </main>
    <script>
            function menuToggle(){
                const sidebar = document.getElementById('sidebar')
                
                sidebar.classList.add('active')
                const main = document.getElementById('profile_main')
    
                const handleClick = function(){
                    sidebar.classList.remove('active')
                    main.removeEventListener('click', handleClick)
                }
    
                setTimeout(function(){
                    main.addEventListener('click', handleClick)
                }, 100)
                
            }
        
        </script>
    
</body>
</html>

app/views/users/about_developers.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>




<main id="about_main">
    <ul class="about_ul">
        <li> By </li>
        <li>
            <ul class="about_ul">
                <li class="student_li">
                    <img src="../assets/bakri.jpg" alt="prenoal_img" class="personal_img"> 
                    <sup><b>Abubker darwish swahli</b></sup>
                </li>
                <li class="student_li"> 
                    <img src="../assets/ahmed.jpg" alt="prenoal_img"class="personal_img"> 
                    <sup><b>Ahmed zaki bashkeel</b></sup>
                </li>
                <li class="student_li">
                    <img src="../assets/mohammed.jpg" alt="prenoal_img" class="personal_img"> 
                    <sup><b>Mohammed ben mohammed swahli</b></sup>
                </li>
                <li class="student_li">
                    <img src="../assets/saeed.jpg" alt="prenoal_img" class="personal_img"> 
                    <sup> <b> Saeed yahia ben waber</b></sup>
                </li>
            </ul>
        </li>
        <li>
            <i><strong>Supervised By</strong></i>
            <ul class="about_ul">
                <li class="student_li"> 
                    <img src="../assets/222.jpg" alt="prenoal_img" class="personal_img"> 
                    <sup> <b>Rasha ben thaleeb</b></sup>
                </li>
            </ul>
        </li>
    </ul>
    </div>
    <!-- <div id="paragrf">
        <p id="pa">
            ththhtt
        </p>
    </div> -->
    <div id="connect">
        <b>phone:05386154 / whatsApp:715571666 / Email:Abubker.darwish@gmail.com</b>
    </div>    
</main>

<div class="right_side">
    <div class="right_div_table">
    <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>
</div>

app/views/users/edit.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_user_users_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="main" class="add_student_main">
    <div class="add_stdudent_div">
        <%= form_for(@user) do |f| %>
        <table summary="Subject form fields">
            <tr>
                <td>Image</td>
                <td><%= f.file_field(:avatar) %></td>
            </tr>
            <tr>
                <td>username</td>
                <td> <%= f.text_field(:username) %></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><%= f.text_field(:email) %></td>
            </tr>
            <tr>
                <td>Role</td>
                <td><%= f.select(:role, ["admin","instructor","student"] ) %></td>
            </tr>
            <tr>
                <td>Status</td>
                <td><%= f.select(:status, ["active","unactive"] ) %></td>
            </tr>
        </table>

            <%= f.submit("Update User") %>
        <% end %>
    </div>
</main>

app/views/users/index.html.erb
<nav>   
    <figure class="top_figure">
       <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="main" class="user_main defult_main">
  <% @users.each do |user| %>  
    <div class="users">
        <img src="<%= user.avatar.url(:medium) %>" alt="fgf" class="user_img">
        <div class="users_info">
            <p> <%= user.username %> </p>
            <p> <%= user.created_at %> </p>
        </div>    
    </div>
  <% end %>  
</main>

<div class="right_side">
        
    <div class="right_div_table">
        <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>

</div>
<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

<script>
    function menuToggle(){
        const sidebar = document.getElementById('sidebar')
        
        sidebar.classList.add('active')
        const main = document.getElementById('main')

        const handleClick = function(){
            sidebar.classList.remove('active')
            main.removeEventListener('click', handleClick)
        }

        setTimeout(function(){
            main.addEventListener('click', handleClick)
        }, 100)
        
    }

</script>

app/views/users/new.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_user_users_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>

<main id="main" class="add_student_main">
    <div class="add_stdudent_div">
        <%= form_for(@user) do |f| %>
            <%# <div class="flex_form">
                <div class="sub_add_stdudent_top">
                    <label>Image</label>
                    <label >Full name</label>
                    <label>Email</label>
                    <label>Password</label>
                    <label>Role</label>
                    <label>Status</label>
                </div>                
                <div class="sub_add_stdudent_down">    
                
                    
                </div>  %>
                        
        <table summary="Subject form fields">
            <tr>
                <td>Image</td>
                <td><%= f.file_field(:avatar) %></td>
            </tr>
            <tr>
                <td>username</td>
                <td> <%= f.text_field(:username) %></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><%= f.text_field(:email) %></td>
            </tr>
            <tr>
                <td>Password</td>
                <td><%= f.password_field(:password) %></td>
            </tr>
            <tr>
                <td>Role</td>
                <td><%= f.select(:role, ["admin","instructor","student"] ) %></td>
            </tr>
            <tr>
                <td>Status</td>
                <td><%= f.select(:status, ["active","unactive"] ) %></td>
            </tr>
        </table>

        <% if flash[:create_user].present? %>
            <p style="color:red; margin:2px"> <%= flash[:create_user] %> </p>
        <% end %>

            <%= f.submit("Add User") %>
        <% end %>
    </div>
</main>

app/views/users/show.html.erb
 <nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_users_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>
 
 
 
 <main id="main" class="profile_main defult_main">
        <div class="profile_up2">
            <% if @current_user&.admin? || @current_user&.instructor? %>
                <img class="first" src="/assets/sttaf.jpeg" alt="">
            <% else %>
                <img class="first" src="/assets/profile.jpg" alt="">
            <% end %>                
            <div class="profile_up2_1">
                <img src="<%= @user.avatar.url(:medium) %>" alt="pdc" class="profile_img"/>
                <b class="name"> <%= @user.username %> </b>
            </div>
            
        </div>
        <!-- <div class="profile_mid">
            
                <div>
                    <strong>Asks:</strong> 
                    <span> 1</span>
                </div>
                <div>
                    <strong>Answer:</strong>
                    <span> 1 </span>
                </div>
                
        </div> -->
        <div class="container">

                <div class="mid_ul_1">
                    <div class="mid_ul_1_1">
                        <li>
                            <a href="<%= user_path(@current_user) %>" class="mid_ul_link"> All Quastion </a>
                        </li>
                        <li>
                            <a href="<%= show_answers_user_path(@current_user) %>" class="mid_ul_link"> All Answers  </a>
                        </li>
                        
                    </div>
                </div>
        </div>

        <% @questions.each do |question| %>
        <div class="quastion_home" onclick="show()">
            <div class="quastion_home_1">
                <h4>Answers</h4>
                <p> <%= question.answers_count %> </p>
            </div>

            <div class="quastion_home_2">
                <h4>Views </h4>
                <p> <%= question.views_count %> </p>
            </div>

            <div class="quastion_home_3_pro">
                <div class="quastion_home_3_1">
                    <img src="<%= question.user.avatar.url(:thumb)%>" alt="the asker" class="saker">
                    <span> <%= question.user.username %> </span>
                        <b> <%= question.created_at %> </b>
                </div>
                <div class="quastion_home_3_2">
                    <div class="quastion_home_3_2_1">
                        <b><a href="<%= question_path(question) %>"> <%= question.title %> </a></b>
                    </div>                    
                </div>
            </div>
            <% if @show_delete_update %>
                <div class="quastion_home_4" id="show">
                    <a href="<%= edit_question_path(question) %>">Update</a>
                    <a href="<%= delete_question_path(question) %>">Delete</a>
                </div>
            <% end %>

        </div>
        <% end  %>

    </main>
    

    <div class="right_side">
        <div class="right_div_table">
                <h3 class="right_div_h3">Personal states</h3>
            <table>
                <!-- <th colspan="2"> states</th> -->
                <tr>
                    <td>Quastions</td>
                    <td> <%= @user.questions.count %> </td>
                </tr>
                <tr>
                    <td>Answers</td>
                    <td> <%= @user.answers.count %> </td>
                </tr>
                <tr>
                    <td>True_answers</td>
                    <td><%= @user.answers.rank_answer.count %></td>
                </tr>
                
            </table>
        </div>
        <% if @current_user&.admin? %>
        <div class="mange_list">
            <h4 class="h4mange">Management</h4>
            <div class="menu">
                <li class="item" id="user">
                    <a href="#user" class="btn"><i class="fas fa-users"> </i> Users</a>
                    <div class="sub_menu">
                        <a href="<%= new_user_path %>" class="sub_menu_link " ><i class="fas fa-user-plus" id="mange_icon"></i> Add</a>
                        <a href="<%= show_users_users_path %>" class="sub_menu_link " ><i class="far fa-eye" id="mange_icon"></i></i> Show</a> 
                    </div>
                </li>
                <li class="item" id="subject">
                    <a href="#subject" class="btn"><i class="fas fa-book"> </i> Subject</a>
                    <div class="sub_menu">
                        <a href="<%= new_subject_path %>" class="sub_menu_link " >Add</a>
                        <a href="<%= subject_path(1) %>" class="sub_menu_link " > <i class="far fa-eye" id="mange_icon"></i></i> Show</a>    
                    </div> 
                </li>
                
            </div>
        </div>
        <% end %>
            <script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

    </main>
    <script>
            function menuToggle(){
                const sidebar = document.getElementById('sidebar')
                
                sidebar.classList.add('active')
                const main = document.getElementById('profile_main')
    
                const handleClick = function(){
                    sidebar.classList.remove('active')
                    main.removeEventListener('click', handleClick)
                }
    
                setTimeout(function(){
                    main.addEventListener('click', handleClick)
                }, 100)
                
            }
            function show(){
                const sidebar = document.getElementById('show')
                
                sidebar.classList.add('show')
                const main = document.getElementById('bod')
    
                const handleClick = function(){
                    sidebar.classList.remove('show')
                    main.removeEventListener('click', handleClick)
                }
    
                setTimeout(function(){
                    main.addEventListener('click', handleClick)
                }, 100)
                
            }
        
        </script>
    
</body>
</html>

app/views/users/show_users.html.erb
<nav>   
    <figure class="top_figure">
       <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_user_users_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>

<main id="main" class="show_student_main">
    <div class="show_stu_content">
        <table class="show_stdent_table">
            <tr>
                <th>Username</th>
                <%# <th>Password</th> %>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Date</th>
                <th>Manage</th>
            </tr>
            <!-- for command for this tr to list all student  -->
             <% @users.each do |user| %>  
            <tr>
                <td><%= user.username %></td>
                <td><%= user.email %></td>
                <td><%= user.role %></td>
                <td><%= user.status %></td>
                <td><%= user.created_at %></td>
                <th class="manage"> 
                    <a href="<%= delete_user_path(user) %>" onclick="sure()">Delete</a>
                    <a href="<%= edit_user_path(user) %>">Update</a>
                </th>
            </tr>
            <% end %>
        </table>
    </div>
</main>