config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # Sessions routes
  get 'logout', :to => 'sessions#destroy'
  resources :sessions

  # Passwords routes
  get 'passworrds/new'
  get 'passworrds/forgot'
  get 'passworrds/new_reset'
  get 'passworrds/reset'

  # Users routes
  resources :users do

    member do
      get :delete
    end

    member do
      get :show_answers
    end

    collection do
      get :about_developers
    end

    collection do
      get :show_users
    end

    collection do
      get :search
    end

    collection do
      get :search_user
    end

  end

  # Subjects routes
  resources :subjects do

    member do
      get :delete
    end

    member do
      get :subject_questions
    end

    member do
      get :unanswered
    end

    member do
      get :answered
    end

    collection do
      get :search
    end

    collection do
      get :search_subject
    end

    member do
      get :delete_question
    end

  end

  # Questions routes
  resources :questions do

    collection do
      get :unanswered
    end

    collection do
      get :answered
    end

    collection do
      get :search
    end

    member do
      get :delete
    end

    member do
      get :delete_question
    end

    member do
      get :d
    end

  end

  # Answers routes
  resources :answers do

    member do
      get :delete
    end

    member do
      get :rank_answer
    end

    member do
      get :create_comment
    end

    member do
      get :new_comment
    end

  end


end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :bigint(8)        not null, primary key
#  answer      :text
#  rank        :boolean          default(FALSE)
#  user_id     :bigint(8)
#  question_id :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord

    ##-----------------------------Reqiurments--------------------##
    scope :rank_answer, -> { where( rank: true ) }

    ##--------------------------Assocciations-------------------##
    has_many :comments, dependent: :destroy
    belongs_to :user, counter_cache: true
    belongs_to :question, counter_cache: true


    ##-----------------------------Callbacks--------------------##

    ##-----------------------------Validations--------------------##
    validates :answer, presence: true


    ##-----------------------------Enums------------------------##

    ##-----------------------------Class methods------------------##
    ##-----------------------------Methods------------------------##

    def set_ranke
        self.rank ? self.rank = false : self.rank = true
        save!
    end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    layout 'admin'

    def create
        @answer = Answer.new( answer_param )
        
        if @answer.save
            flash[:create_answer] = nil
            redirect_to( question_path(@answer.question) )
        else
            flash[:create_answer] = @answer.errors.full_messages
            redirect_to( question_path(session[:question_id]) )
        end
    end

    def edit
        @answer = Answer.find( params[:id] )
    end

    def update
        @answer = Answer.find(params[:id])

        if @answer.update_attributes(answer_params)
            redirect_to( question_path(@answer.question) )
        else
            render('edit')
        end
    end

    def delete
        @answer = Answer.find(params[:id])
        @answer.destroy
        redirect_to( question_path(@answer.question) )
    end

    def destroy
    
    end

    def rank_answer
        @answer = Answer.find( params[:id] )
        @answer.set_ranke
        redirect_to ( question_path(@answer.question) )
    end

    def new_comment
        @answer = Answer.find( params[:id] )
        @comments = @answer.comments.reverse
        session[:answer_id] = @answer.id
    end

    def create_comment
        @comment = Comment.new( comment_params )
        
        if @comment.save
            redirect_to( new_comment_answer_path(session[:answer_id]) )
        else
            redirect_to( question_path(session[:question_id]) )
        end
    end

    private

    def answer_params
        params[:answer][:user_id] = @current_user.id
        params[:answer][:question_id] = session[:question_id] 
        params.require(:answer).permit( :answer ,:question_id, :user_id )
    end

    def answer_param
        params[:user_id] = @current_user.id
        params[:question_id] = session[:question_id] 
        params.permit( :answer ,:question_id, :user_id )
    end

    def comment_params
        params[:user_id] = @current_user.id
        params[:answer_id] = params[:id]
        params.permit(:comment, :user_id, :answer_id)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/edit.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="ask_main" >
    <div>
    <%= form_for(@answer) do |f| %>
        <ul id="ulask">
            <li>
                <label for="">Answer</label>   
            </li>
            <li>
                <%= f.text_area(:answer, size: '114x30') %>
            </li>
        </ul>
        <div class="related_sub">
            <%= f.submit("Update Answer") %>
        </div>
    <% end %>
    </div>      
</main>

app/views/answers/new_comment.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>

<main id="main" class="defult_main">
    <!-- <div class="the_title">
        <strong>the title of quastion </strong>
    </div> -->
    
    
    <div class="answer">
        <div class="answer_up" >
            <div class="answer_up_left" >
                <% if @answer.rank %>
                    <i class="fas fa-star" id="star"></i>
                <% else %>
                    <i class="fas fa-star" id="star" style="color:white"></i>
                <% end %>
                
                <% if @current_user.admin? || @current_user.instructor? %>
                    <a href="<%= rank_answer_answer_path(@answer) %>" class="link_rank"> Rank </a> 
                <% end %>
            </div>
            <div class="answer_up_right">
                <div class="quastion_home_3_1 ">
                    <img src="<%= @answer.user.avatar.url(:thumb)%>" alt="the asker" class="asker">
                    <span> <%= @answer.user.username %> </span>
                    <b> <%= @answer.created_at %> </b>
                </div>
                <pre>
                    <%= @answer.answer %> 
                </pre>
            </div>
        </div>

        <div class="answer_down" >
                <a href="#"><i class="fas fa-thumbs-up"></i> like</a>
                <a href="#"> <i class="fas fa-thumbs-down"></i> dislike</a>
                <a href="#" ><i class="far fa-comment"></i>comment</a>
                <% if @current_user.username == @answer.user.username %>
                    <a href="<%= edit_answer_path(@answer) %>"><i class="far fa-comment"></i> Update</a>
                    <a href="<%= delete_answer_path(@answer) %>"><i class="far fa-comment"></i> Delete</a>
                <% end %>    
        </div>
        <div class="comment_div" id="comment">
            <div class="input_comment_div">

                <%= form_tag(create_comment_answer_path(@answer), :method => :get) do %>
                        <%= text_field_tag(:comment, params[:comment]) %>
                        <%= submit_tag("Enter") %>
                <% end %>
                
            </div>    
                
            <div class="show_comment">
                <% @comments.each do |comment| %>
                    <div class="comment_info">
                        <div class="quastion_home_3_1 ">
                            <img src="<%= comment.user.avatar.url(:thumb)%>" alt="the asker" class="asker">
                            <span> <%= comment.user.username %> </span>
                        </div>
                        <span style="margin-left:40px; margin-top:5px;display:block;"> <%= comment.comment %></span>
                    </div>
                <% end %>
            </div>  
        </div>
    </div>
     
</main>

<div class="right_side" id="right_side">
        
    <div class="right_div_table">
        <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>

</div>   
 