config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # Sessions routes
  get 'logout', :to => 'sessions#destroy'
  resources :sessions

  # Passwords routes
  get 'passworrds/new'
  get 'passworrds/forgot'
  get 'passworrds/new_reset'
  get 'passworrds/reset'

  # Users routes
  resources :users do

    member do
      get :delete
    end

    member do
      get :show_answers
    end

    collection do
      get :about_developers
    end

    collection do
      get :show_users
    end

    collection do
      get :search
    end

    collection do
      get :search_user
    end

  end

  # Subjects routes
  resources :subjects do

    member do
      get :delete
    end

    member do
      get :subject_questions
    end

    member do
      get :unanswered
    end

    member do
      get :answered
    end

    collection do
      get :search
    end

    collection do
      get :search_subject
    end

    member do
      get :delete_question
    end

  end

  # Questions routes
  resources :questions do

    collection do
      get :unanswered
    end

    collection do
      get :answered
    end

    collection do
      get :search
    end

    member do
      get :delete
    end

    member do
      get :delete_question
    end

    member do
      get :d
    end

  end

  # Answers routes
  resources :answers do

    member do
      get :delete
    end

    member do
      get :rank_answer
    end

    member do
      get :create_comment
    end

    member do
      get :new_comment
    end

  end


end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id                  :bigint(8)        not null, primary key
#  name                :string
#  questions_count     :integer          default(0)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class Subject < ApplicationRecord

    ##-----------------------------Reqiurments--------------------##

    ##--------------------------Assocciations-------------------##
    has_many :questions, dependent: :destroy


    ##-----------------------------Callbacks--------------------##

    ##-----------------------------Validations--------------------##
    has_attached_file :avatar , styles: { medium: "300x300>", thumb: "40x40>" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    validates :name, presence: true,
                        uniqueness: true


    ##-----------------------------Enums
    ##-----------------------------Class methods------------------##
    ##-----------------------------Methods------------------------##

    def sub
        2 - 5
    end


end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  before_action :set_subject, only: [:subject_questions, :unanswered, :answered, :edit, :update, :delete]

  def index
    @subjects = Subject.all
  end

  def subject_questions
    session[:subject_id] = params[:id]
    @questions = @subject.questions.newest
  end

  def unanswered
    @questions = @subject.questions.unanswered
    render('subject_questions')
  end

  def answered
    @questions = @subject.questions.answered
    render('subject_questions')
  end

  def search
    @subject = Subject.find(session[:subject_id])
    @questions = @subject.questions.ransack( title_cont: params[:search] ).result
    render('subject_questions')
  end

  def search_subject
    @subjects = Subject.ransack( name_cont: params[:search] ).result
    render('show')
  end

  def show
    @subjects = Subject.all
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new( subject_params )
    if @subject.save
      flash[:create_subject] = nil
      redirect_to(subject_path(1))
    else
      flash[:create_subject] = @subject.errors.full_messages
      render('new')
    end
  end

  def edit
  end

  def update
    if @subject.update_attributes( subject_params )
      redirect_to( subject_path(1) )
    else
      render('edit')
    end
  end

  def delete
    @subject.destroy
    redirect_to( subject_path(1) )
  end

  def delete_question
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to(subject_questions_subject_path(session[:subject_id]))
  end

  def destroy
  end


  private

  def subject_params
    params.require(:subject).permit( :name, :avatar )
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/edit.html.erb
  <nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_subject_subjects_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="main" class="add_student_main">
    <div class="add_stdudent_div">
        <%= form_for(@subject) do |f| %>       
        <table summary="Subject form fields">
            <tr>
                <td>Image</td>
                <td><%= f.file_field(:avatar) %></td>
            </tr>
            <tr>
                <td>Name</td>
                <td> <%= f.text_field(:name) %></td>
            </tr>
        </table>

        <%= f.submit("Update Subject") %>
    <% end %>
    </div>
</main>

app/views/subjects/index.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_questions_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>


<main id="main" class="user_main defult_main">
  <% @subjects.each do |subject| %>  
    <div class="users">
        <img src="../assets/alkaff.jpg" alt="fgf" class="user_img">
        <div class="sub_info">
            <span><a href="<%= subject_questions_subject_path(subject) %>"> <%= subject.name %>  </a></span>                       
        </div>    
    </div>
  <% end %>  
</main>

<div class="right_side">
        
    <div class="right_div_table">
        <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>

</div>
<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

<script>
    function menuToggle(){
        const sidebar = document.getElementById('sidebar')
        
        sidebar.classList.add('active')
        const main = document.getElementById('main')

        const handleClick = function(){
            sidebar.classList.remove('active')
            main.removeEventListener('click', handleClick)
        }

        setTimeout(function(){
            main.addEventListener('click', handleClick)
        }, 100)
        
    }

</script>

app/views/subjects/new.html.erb
  <nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_subject_subjects_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>

<main id="main" class="add_student_main">
    <div class="add_stdudent_div">
        <%= form_for(@subject) do |f| %>       
        <table summary="Subject form fields">
            <tr>
                <td>Name</td>
                <td> <%= f.text_field(:name) %></td>
            </tr>
        </table>
        
        <% if flash[:create_subject].present? %>
            <p style="color:red; margin:2px"> <%= flash[:create_subject] %> </p>
        <% end %>

        <%= f.submit("Add Subject") %>
    <% end %>
    </div>
</main>


<%# <div class="right_side"> %>

<%# </div> %>

app/views/subjects/show.html.erb
  <nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_subject_subjects_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>
  
  <main id="main" class="show_student_main">
        <div class="show_sub_content">
            <table class="show_subject_table">
                <tr>
                    <th >Name</th>
                    <th>Manage</th>
                </tr>
                <!-- for command for this tr to list all student  -->
                <% @subjects.each do |subject| %>  
                <tr>
                    <td><%= subject.name %></td>
                    <td class="manage"> 
                        <a href="<%= delete_subject_path(subject) %>">Delete</a>
                        <a href="<%= edit_subject_path(subject) %>">Update</a>
                    </td>
                </tr>
                <% end %>
            </table>
        </div>

    </main>

app/views/subjects/subject_questions.html.erb
<nav>   
    <figure class="top_figure">
        <span class="logo_span">
            CE-learner <br> Stack Exchange
        </span>
            
    </figure>

    <i class="fas fa-bars" onclick="menuToggle()" id="menu_button"></i>

    <%= form_tag(search_subjects_path, :method => :get) do %>
        <div id="search_bar" >                    
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag("Search") %>
        </div>
    <% end %>
    
    <div class="nav_right">  
        
        <figure class="down_figure" >
            <div>
                <a href="<%= user_path(@current_user) %>" class="avtar_link"><img src="<%= @current_user.avatar.url(:thumb) %>s" alt="logo" class="avatar"></a>
            </div> 
            <span><a href="<%= user_path(@current_user) %>"> <%= @current_user.username %> </a></span>
        </figure>
        
    </div>
</nav>




<main id="main" class="defult_main">
        <div class="container">

            <div class="mid_ul_1">
                <div class="mid_ul_1_1">
                    <li>
                    <a href="<%= subject_questions_subject_path(@subject) %>" class="mid_ul_link"> All Quastion </a>
                </li>
                <li>
                    <a href="<%= unanswered_subject_path(@subject) %>" class="mid_ul_link"> Non Answered  </a>
                </li>
                <li>
                    <a href="<%= answered_subject_path(@subject) %>" class="mid_ul_link">  Answered  </a>
                </li>
                </div>
                
                <div class="mid_ul_1_2">
                    
                    <li>
                    <a href="" class="mid_ul_link">last week  </a>
                </li>
                <li>
                    <a href="" class="mid_ul_link">  last month</a>
                </li>
                </div>

            </div>
            
            <div class="askdiv">
                <a href="<%= new_question_path %>" class="mid_ul_link">Ask Quastion <i class="fas fa-question"></i> </a>
            </div>
        </div>

        <% @questions.each do |question| %>
        <div class="question_container" id="scroll"  data-simplebar>
            <div class="quastion_home">
                <div class="quastion_home_1">
                    <h4>Answers</h4>
                    <p> <%= question.answers_count %> </p>
                </div>

                <div class="quastion_home_2">
                    <h4>Views </h4>
                    <p> <%= question.views_count %> </p>
                </div>

                <div class="quastion_home_3">
                    <div class="quastion_home_3_1">
                        <img src="<%= question.user.avatar.url(:thumb)%>" alt="the asker" class="saker">
                        <span> <%= question.user.username %> </span>

                        <p style="display: none"><%= x = false %></p>
                        <% question.answers.each do |answer| %>
                        
                            <% if answer.rank %>
                                <p style="display: none"> <%= x = true %> </p>
                            <% end %>    
                        <% end %>
                        <% if x %>    
                            <i class="fas fa-star" id="star_main"></i>
                        <% else %>
                            <i class="fas fa-star" id="star_main" style="color:white"></i>
                        <% end %>

                        <% if @current_user.admin? %>
                            <a href="<%= delete_question_subject_path(question) %>"> Delete</a>
                        <% end %>

                        <b> <%= question.created_at %> </b>
                    </div>
                <div class="quastion_home_3_2">
                    <div class="quastion_home_3_2_1">
                        <b><a href="<%= question_path(question) %>"> <%= question.title %> </a></b>
                    </div>                    
                </div>
            </div>
        </div>
        <% end %>    
        
        
    </main>



<div class="right_side">
        
    <div class="right_div_table">
        <h3 class="right_div_h3">Site states</h3>
        <table>
            <th colspan="2">Site states</th>
            <tr>
                <td>Quastions</td>
                <td><%= Question.count %></td>
            </tr>
            <tr>
                <td>Answers</td>
                <td> <%= Answer.count %> </td>
            </tr>
            <tr>
                <td>True_answers</td>
                <td><%= Answer.rank_answer.count %></td>
            </tr>
            <tr>
                <td>Users</td>
                <td> <%= User.count %> </td>
            </tr>
            <tr>
                <td>Subjects</td>
                <td> <%= Subject.count %> </td>
            </tr>
        </table>
    </div>

</div>
<script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>



<script>
    function menuToggle(){
        const sidebar = document.getElementById('sidebar')
        
        sidebar.classList.add('active')
        const main = document.getElementById('main')

        const handleClick = function(){
            sidebar.classList.remove('active')
            main.removeEventListener('click', handleClick)
        }

        setTimeout(function(){
            main.addEventListener('click', handleClick)
        }, 100)
        
    }

</script>